spring.application.name=jl-gestao

spring.datasource.url=jdbc:postgresql://localhost:5432/jl_gestao
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
